exclude: ["README.md", "package.json", "package-lock.json", "gulpfile.js", ".DS_Store", "node_modules", 'Gemfile', "Gemfile.lock", "vendor/bundle/", "vendor/gems/", "vendor/cache/", "vendor/ruby/", "robots.txt"]
include:
   - "_headers"

keep_files: 
   - 'css' 
   - 'js' 
   - 'img' 
   - 'assets'

permalink: pretty

url: https://example.com/
baseurl: ""
website-date: 17th March 2019
location: England
title: Business name
company: Comapny name
email: example@gmail.com
mobile: 0000 0000
logo: img/example.svg

meta: Website metadata goes here

facebook: https://www.facebook.com/

designer-url: https://davidlowerdesigns.com/
designer-name: David Lower
designer-company: David Lower Designs

plugins:
  - jekyll-sitemap
